### ISSUE TITLE
extending the MIST age grid to 13.7 Gyr

### ISSUE THREAD

**Issue by jajohnson51** [astropy/SPISEA#66]
It would be very helpful to have the MIST grid extended to cover the oldest clusters, so essentially all the way to age of the Universe, instead of ending at 10 billion years. Would that be possible?
Thanks,
Jennifer Johnson

**Comment by jajohnson51** [comment]
Hi Matt,
Thanks for the info on the Parsec grid and for updates on the MIST models. I would rather have the spread in metallicity and just lump all the old things together for the time being, so I'll happily keep using the current MIST ones.
Jennifer

**Comment by mwhosek** [comment]
Hi Jennifer,

Sounds good! Sorry for the delay on this...my schedule has been swamped the past few weeks. But, I will let you know as soon as we have the extended MIST grid pushed up into the main code release. 

-Matt

**Comment by mwhosek** [comment]
Hi Jennifer,

Sorry for the long delay in this! But, I'm happy to report that we've finally extended the MIST evolution model grid to span logAge = 5.0 -- 10.30, the full age range the MIST folks offer. SPISEA v2.1.4 (just released) has this update. Note that in addition to getting the updated code via `git pull origin main` in your spisea code directory, you'll also need to redownload the `spisea_models.tar.gz` file from the [installation page](https://spisea.readthedocs.io/en/latest/getting_started.html) and unzip the contents in your models directory in order to get the new functionality.

Thanks again for your suggestion! Let us know if you run into any trouble with the code update.
Matt
