### ISSUE TITLE
pytest : ModuleNotFoundError: No module named 'pytest_astropy_header' in  SPISEA-2.1.9

### ISSUE THREAD

**Issue by Astro-Lee** [astropy/SPISEA#91]
- version: SPISEA-2.1.9

When I run `pytest`, I have encountered the following error:

![pytest](https://user-images.githubusercontent.com/61745903/212405360-b171808f-73b1-4901-83d9-7b19a787d6e6.jpg)

Thanks!

**Comment by mwhosek** [comment]
Hello,

Thanks for reporting this bug! I suspect this might be a SPISEA dependence that we neglected to add to our documentation. In this case, the missing package is [pytest-astropy-header](https://github.com/astropy/pytest-astropy-header), which we need for the testing suite. 

It looks like you can install pytest-astropy-header via pip (see package link above for instructions). If you are using anaconda for your python environment, you can also install it by:

`conda install pytest-astropy-header`

Let us know if this fixes the issue, and we will update the install documentation accordingly. Otherwise, we'll continue to debug :).

Thanks for your interest in SPISEA!
Matt

**Comment by Astro-Lee** [comment]
`pytest` passed! 👍 

![image](https://user-images.githubusercontent.com/61745903/212419016-a3f87d51-5c9f-42b4-8187-9b85004bc033.png)

Thanks!
